### ISSUE TITLE
SSO logout redirect uri new spec

### ISSUE THREAD

**Issue by xkotj** [openshift/enhancements#1219]
Hello,
I would like to explain need for a **post_logout_redirect_uri** and **id_token_hint** parameters in logoutRedirect config
While integrating SSO (Keycloak 19, OIDC) with OKD I encountered there is a no possibility to include id_token_hint as a variable  in logoutRedirect URI configuration.

https://docs.openshift.com/container-platform/4.11/web_console/configuring-web-console.html

Keycloak 18+ deprecated logout parameter **redirect_uri** 
Reason: _While that implementation was easy to use, it had potentially negative impact on performance and security_
https://www.keycloak.org/2022/04/keycloak-1800-released#_openid_connect_logout
https://www.keycloak.org/2022/07/keycloak-1900-released_oidc_logout_changes

This will be removed probably in version 23.

As a workaround for this issue is to start Keycloak 18+ with legacy parameter 
bin/kc.[sh|bat] **--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true** start

After applying workaround user is correctly redirected to OKD login screen after logout.

For future releases of Keycloak it is needed feature in OKD to comply with OIDC spec - OpenID Connect RP-Initiated Logout specification

Best Regards,
JK

**Comment by dverbeek84** [comment]
/reopen
 This is still not working.
