### ISSUE TITLE
kube-apiserver/auto-cert-recovery.md

### ISSUE THREAD

**Issue by deads2k** [openshift/enhancements#157]
https://github.com/openshift/enhancements/blob/master/enhancements/kube-apiserver/auto-cert-recovery.md

/assign @tnozicka

**Comment by tnozicka** [comment]
https://github.com/openshift/cluster-kube-apiserver-operator/pull/663
https://github.com/openshift/cluster-kube-apiserver-operator/pull/635
https://github.com/openshift/library-go/pull/645
