### ISSUE TITLE
vSphere IPI Zonal - Streched Clusters

### ISSUE THREAD

**Issue by ddcdk** [openshift/enhancements#1570]
Hi,
With VMware Streched on a HCI infrastructure we have a VMware cluster streched on two different sites. We have from VMware view one datacenter, one clusters with esxi servers on one site and esxi servers on an other site (Let say 5 servers on a site, and 5 servers on the other site).Storage is replicated synchonously, datastores are then viewed by all nodes.
When i deploy an openshift cluster i would like that my master and worker nodes will be deployed on one site only, this means that only esxi servers on this site have to be used.

Thanks,
Delfim.

**Comment by jcpowermac** [comment]
This will be resolved by #1677
