### ISSUE TITLE
authentication/separate oauth-apiserver

### ISSUE THREAD

**Issue by deads2k** [openshift/enhancements#176]
- [ ] image for the oauth-apiserver needs to be created
- [ ] image for the oauth-apiserver needs to be in the payload (must be referenced from an operator)
- [ ] authentication operation needs inspection to be sure that proper unioning of status works
- [ ] oauth-apiserver needs to be manually put into a cluster using the resources that we'll later use in the operator.
- [ ] oauth-apiserver needs to actually work (no one has checked yet)  I think @polynomial could help here.
- [ ] some controllers should be extracted into an apiserver-controllers package (@stlaz  is doing this now)
- [ ] various helpers and mutators for operator workload manifests need to become congruent and viable for re-use
- [ ] the exact backoff mechanism for the "stop managing this apiservice" needs to be coded with a unit test synthetically producing an "upgrade, downgrade, upgrade" path.  I think @polynomial would be a big help here.

**Comment by polynomial** [comment]
unsure how i got mentioned here, but hello! @deads2k
