### ISSUE TITLE
etcd operator

### ISSUE THREAD

**Issue by hexfusion** [openshift/enhancements#222]
https://github.com/openshift/enhancements/blob/master/enhancements/etcd/cluster-etcd-operator.md

**Perf**
- [x] problems bootstrapping cluster @alaypatel07 

**Metal**
- [x] ipv4 works on 3/4 (asked in slack channel)
- [x] ipv6 works on 3/4 (asked in slack channel)

**IPv6**
- [x] azure is broken on pivot @deads2k 
      1. https://github.com/openshift/cluster-etcd-operator/pull/173
- [x] azure bootstrap is broken @hexfusion 
  - [x] https://github.com/openshift/cluster-etcd-operator/pull/154
  - [x] https://github.com/openshift/cluster-etcd-operator/pull/175
  - [x] stop using invalid bootstrapIP from installer https://github.com/openshift/installer/pull/3175 @deads2k 
  - [x] use correct bootstrapIP in static pods https://github.com/openshift/cluster-etcd-operator/pull/200 @deads2k 

**bootstrapping**
- [x] keep bootstrap kube-apiserver up @deads2k 
      1. https://github.com/openshift/cluster-etcd-operator/pull/179
- [x] real kube-apiserver to only use real etcd  @deads2k 
      1. https://github.com/openshift/cluster-kube-apiserver-operator/pull/772

**shutdown clusters don't start back up**
- [x] need to bypass the member lookup when there is no cluster
  - [x] create a golang command so we can follow the logic.  @deads2k https://github.com/openshift/etcd/pull/28
  - [x] use golang command in our static pods @deads2k  https://github.com/openshift/cluster-etcd-operator/pull/185
  - [x] update golang command to have a memory. - this isn't needed because we can use presence of data-dir to skip.  Thanks @alaypatel07 and @retroflexer  
  - [x] https://github.com/openshift/cluster-etcd-operator/pull/203 @alaypatel07 

**blocker bugs**
- [x] port conflict @p0lyn0mial https://bugzilla.redhat.com/show_bug.cgi?id=1806579 - https://github.com/openshift/cluster-etcd-operator/pull/226
- [x] this is 4.2 to 4.3.  Not part of this feature. cert problem found by wking @sttts is finding someone
- [x] `oc rsh` doesn't auto-start with work etcdctl.  this is needed for maintenance. - @sanchezl https://bugzilla.redhat.com/show_bug.cgi?id=1805981 https://github.com/openshift/cluster-etcd-operator/pull/207
- [x] upgrade failures where etcd appears to be unavailable @sanchezl https://bugzilla.redhat.com/show_bug.cgi?id=1807194

**Tests we think should work**
- [x]  All nodes being shut off at the same time and restarted. - tested by QE and appears to be working.
- [x]  IP address change of a single member @hexfusion 
- [x]  debugging and detection when DNS information for one member is lost @sanchezl https://github.com/openshift/cluster-etcd-operator/pull/225.  It degrades nicely, but we don't like degrading during upgrade.  May end up switching to IPs
- [x]  Addition of a new member when there is significant etcd data. - verified by @alaypatel07  by adding a fourth member.
- [x]  Upgrade, downgrade, re-upgrade @alaypatel07 

**Tests we think should fail**
- [x]  If one master is lost, instructions for how to.
   - [x]  create a new master that joins the cluster
   - [x]  removal of the old master from the cluster
- [x] Restoring etcd when no members start up correctly
  - [x]  Changes to the etcd-quorum recovery steps
  - [x]  restore etcd from backup  @retroflexer 
- [x] Make etcd consistent when one member needs to be removed.  Ideally this becomes "remove etcd member, rollout".  with https://github.com/openshift/etcd/pull/29 it may become that because we can auto-remove a bad data-dir.  We may need to find a way to mark a node as "don't include in etcd"
  - [x]  Removal of a member from the etcd cluster @retroflexer (probably should be @alaypatel07)
  - [x]  Recovery of a member with a bad data-dir.  @retroflexer 
  - [x]  replace an existing member @hexfusion 
- [ ] restore etcd when 2 masters are replaced. @hexfusion
- [ ]  IP address change of all members

**Comment by retroflexer** [comment]
I am working on:
1. Restoring a cluster to previous state
2. etcd-quorum recovery steps
3. Removal of a member from etcd cluster
4. Recovery of a member with a bad data-dir

**Comment by retroflexer** [comment]
@deads2k I am not suresh gaikwad. My handle here is @retroflexer.
