### ISSUE TITLE
Multi-tenancy and Elasticsearch rollover

### ISSUE THREAD

**Issue by sbarre-esit** [openshift/enhancements#375]
Re: LOG-545: Cluster logging Elasticsearch rollover data design #108

Will there be an easy way to see how much disk space is consumed per application namespace? On my multi-tenant cluster I've occasionally had one namespace accidentally leave their logging at DEBUG when they went to production. When I got disk full alerts from ES I was able to query ES for all indexes sorted by size and see the culprit quickly and then contact the appropriate person for that namespace to get them to turn their logging back down.

I worry that by merging all the logs into once index it will be harder to find the "noisy neighbour" and have them adjust their settings.

**Comment by sbarre-esit** [comment]
Hmm, maybe I could use [Terms Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) to count the number of records for each namespace?

**Comment by lukas-vlcek** [comment]
Correct, you can use terms agg to do counts by namespace and if you want to be cool you can do second level aggregation to see counts of records at individual log levels per namespace. (But this assumes the log level is correctly recorded which I am not sure is the case all the time).

You can also use histogram aggregation over time with nested term aggregation by namespace to see the changes during the time (if there is a sudden spike in some namespace then this would be probably the best visualization).

**Comment by lukas-vlcek** [comment]
There is also this plugin https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-size.html that could be used to do calculations based on the size of original documents (ie. individual logs) but OCP logging does not include this plugin atm.
