### ISSUE TITLE
API counts

### ISSUE THREAD

**Issue by deads2k** [openshift/enhancements#731]
**Blocker**
- [x] unit tests for conversion
- [x] unit tests for restarted process
- [ ] build a map of GVR to removed release
- [ ] unit test to maintain map of GVR to removed
- [x] new API for all API types
- [x] move removedInRelease to status
- [x] label indicating removed release for selection
- [x] new field for total access each hour and total in 24h
- [x] remove lastupdatetime
- [x] allow spec to indicate how many users to include?
- [x] specify GET columns
- [ ] fix bug where only high counts are honored across intervals.

**Future**
- [ ] update stats during shutdown

**Comment by sanchezl** [comment]
- [x] [unit tests for conversion](https://github.com/openshift/kubernetes/pull/675)
