### ISSUE TITLE
oc debug enhancement

### ISSUE THREAD

**Issue by kaovilai** [openshift/enhancements#92]
**Summary**
As currently implemented, oc debug can accept single _command without parameters_ such as `oc debug [node] -- ls`
This is quite restrictive and limits possible actions that can be done to the nodes.

I propose that `oc debug` be enhanced in a way that will allow commands with parameters to be used to perform such actions without having to enter the node/container's shell first, and having to exit later..

Alternatively, implement a new function to allow administrative user to perform actions on the nodes.

**Background**
A few months ago during my 🔴⛑ internship, I had developed an [ansible role](https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp4-workload-open-data-hub) for deploying rook-ceph on openshift.

During "[teardown](https://rook.io/docs/rook/v1.1/ceph-teardown.html)", it is required that  _/var/lib/rook: Path on each host in the cluster where configuration is cached by the ceph mons and osds_ be deleted.

This was done by using `oc debug [NODENAME]` followed by
`rm -rf /host/var/lib/rook`
and `exit`.

This was tedious and you had to do it for each worker node during troubleshooting between rook-ceph installs/removals. I was [able to make the repeating process slightly easier](https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp4-workload-open-data-hub#troubleshooting) by using a for loop in the shell to iterate through each worker node, but still had to manually press return by hand for each worker node.

**Comment by soltysh** [comment]
This looks like a bug to me, rather than enhancement, moving to https://bugzilla.redhat.com/show_bug.cgi?id=1791374

**Comment by ingvagabund** [comment]
@kaovilai checking the latest version of `oc`, command with parameters are accepted:

```
$ oc debug -q node/ip-10-0-134-68.us-west-1.compute.internal -- mkdir -p /host/var/lib/rook
$ oc debug -q node/ip-10-0-134-68.us-west-1.compute.internal -- ls -l -d /host/var/lib/rook
drwxr-xr-x. 2 root root 6 May 15 08:59 /host/var/lib/rook
$ oc debug -q node/ip-10-0-134-68.us-west-1.compute.internal -- rm -rf /host/var/lib/rook
$ oc debug -q node/ip-10-0-134-68.us-west-1.compute.internal -- ls -l -d /host/var/lib/rook
ls: cannot access /host/var/lib/rook: No such file or directory
error: non-zero exit code from debug container
```

I can't find any particular change in the code adding the support. Can you check the latest version of `oc` to see if your issue is solved? What's the version of `oc` you used to reproduce your issue with?

**Comment by kaovilai** [comment]
@ingvagabund 
> I can't find any particular change in the code adding the support. Can you check the latest version of `oc` to see if your issue is solved? What's the version of `oc` you used to reproduce your issue with?

As old as 2016 (https://www.mankier.com/1/oc-debug) Not sure when `-q` was added.

I won't be able to try the latest version anytime soon. Glad there exists a version where it works though.
